export const books = [
  {
    title:
      "Fundamentos do React JS: Aprenda a bilioteca mais famosa de front-end através de exercícios e projetos",
    category: "Tecnologia e Computação",
    author: "Matheus Battisti",
    urlImage: "https://m.media-amazon.com/images/I/71yde-JXeyL._SL1500_.jpg",
  },
  {
    title: "Estruturas de dados e algoritmos com JavaScript",
    category: "Tecnologia, Programação",
    author: "Loiane Groner",
    urlImage:
      "https://books.google.com.br/books/publisher/content?id=0nWKDwAAQBAJ&hl=pt-BR&pg=PA4&img=1&zoom=3&bul=1&sig=ACfU3U1Rntr1z1ysc0uIvTy9xDJw7YvgKQ&w=1280",
  },
  {
    title: "Código Limpo",
    category: "Tecnologia, Programação",
    author: "Robert C. Martin",
    urlImage:
      "https://http2.mlstatic.com/D_NQ_NP_677433-MLU72592365557_102023-O.webp",
  },
  {
    title: "A menina que roubava livros",
    category: " Romance, Ficção juvenil, Ficção histórica,",
    author: "Markus Zusak",
    urlImage:
      "https://books.google.com.br/books/content?id=-_MMbijUmTEC&hl=pt-BR&pg=PP1&img=1&zoom=3&bul=1&sig=ACfU3U1tp8sOMKZud7hUmlJIIg9fwj8yZA&w=1280",
  },
];

export const categoriesBooks = [
  "Ficção Científica",
  "Fantasia",
  "Romance",
  "Suspense e Mistério",
  "Terror",
  "Biografia e Autobiografia",
  "História",
  "Ficção Histórica",
  "Autoajuda",
  "Negócios e Economia",
  "Finanças Pessoais",
  "Tecnologia e Computação",
  "Saúde e Bem-Estar",
  "Culinária e Gastronomia",
  "Arte e Fotografia",
  "Viagem e Turismo",
  "Poesia",
  "Humor",
  "Esporte e Lazer",
  "HQ e Mangás",
  "Juvenil e Adolescente",
  "Infantil",
  "Filosofia",
  "Psicologia",
  "Religião e Espiritualidade",
  "Ciências Sociais",
  "Política e Ciências Humanas",
  "Educação",
  "Direito",
  "Medicina",
  "Engenharia",
  "Ciências Exatas",
  "Ciências Naturais",
  "Linguística e Idiomas",
  "Guia de Estudo e Referência",
  "Literatura Brasileira",
  "Literatura Estrangeira",
  "Clássicos",
  "Teatro e Dramaturgia",
  "Ensaios",
  "Mitologia e Lendas",
  "Contos e Crônicas",
  "Guias de Estilo de Vida",
  "Espiritualidade e Esoterismo",
  "Aventura",
  "Distopia",
  "Cyberpunk",
  "Steampunk",
  "Apocalíptico e Pós-Apocalíptico",
  "Viagem no Tempo",
  "Fantasia e Ficção Científica",
  "Western",
  "Novela Gráfica",
  "Animais e Natureza",
  "Ciência e Tecnologia",
  "Dicionários e Enciclopédias",
  "Jardinagem e Horticultura",
  "Design e Moda",
  "Música",
  "Cinema e TV",
  "Arquitetura",
  "Gestão e Liderança",
  "Religião Comparada",
  "Antropologia",
  "Sociologia",
  "Ecologia e Meio Ambiente",
  "Feminismo e Estudos de Gênero",
  "Trabalho e Carreira",
  "Moda e Beleza",
  "Parentalidade e Relacionamentos",
  "Áudio Livros",
  "Livros de Bolso",
  "Pintura e Desenho",
].sort();

export const addBook = (title, category, author, urlImage) => {
  const book = {
    title: title,
    category: category,
    author: author,
    urlImage: urlImage,
  };
  books.push(book);
};
