const categoriesBooks = [
  "Ficção Científica",
  "Fantasia",
  "Romance",
  "Suspense e Mistério",
  "Terror",
  "Biografia e Autobiografia",
  "História",
  "Ficção Histórica",
  "Autoajuda",
  "Negócios e Economia",
  "Finanças Pessoais",
  "Tecnologia e Computação",
  "Saúde e Bem-Estar",
  "Culinária e Gastronomia",
  "Arte e Fotografia",
  "Viagem e Turismo",
  "Poesia",
  "Humor",
  "Esporte e Lazer",
  "HQ e Mangás",
  "Juvenil e Adolescente",
  "Infantil",
  "Filosofia",
  "Psicologia",
  "Religião e Espiritualidade",
  "Ciências Sociais",
  "Política e Ciências Humanas",
  "Educação",
  "Direito",
  "Medicina",
  "Engenharia",
  "Ciências Exatas",
  "Ciências Naturais",
  "Linguística e Idiomas",
  "Guia de Estudo e Referência",
  "Literatura Brasileira",
  "Literatura Estrangeira",
  "Clássicos",
  "Teatro e Dramaturgia",
  "Ensaios",
  "Mitologia e Lendas",
  "Contos e Crônicas",
  "Guias de Estilo de Vida",
  "Espiritualidade e Esoterismo",
  "Aventura",
  "Distopia",
  "Cyberpunk",
  "Steampunk",
  "Apocalíptico e Pós-Apocalíptico",
  "Viagem no Tempo",
  "Fantasia e Ficção Científica",
  "Western",
  "Novela Gráfica",
  "Animais e Natureza",
  "Ciência e Tecnologia",
  "Dicionários e Enciclopédias",
  "Jardinagem e Horticultura",
  "Design e Moda",
  "Música",
  "Cinema e TV",
  "Arquitetura",
  "Gestão e Liderança",
  "Religião Comparada",
  "Antropologia",
  "Sociologia",
  "Ecologia e Meio Ambiente",
  "Feminismo e Estudos de Gênero",
  "Trabalho e Carreira",
  "Moda e Beleza",
  "Parentalidade e Relacionamentos",
  "Áudio Livros",
  "Livros de Bolso",
  "Pintura e Desenho",
].sort();

export default categoriesBooks;
